#! /bin/bash
## customer_id,flight_id"
echo "customer_id,flight_id" > flightReservation.csv
for i in {1..1000000}
do
	id_customer=`shuf -i 1-100000 -n 1`
	id_flight=`shuf -i 1-100000 -n 1`
	echo "$id_customer,$id_flight" >> flightReservation.csv
done
